### ISSUE TITLE
kivy ffpyplayer | video not working

### ISSUE THREAD

**Issue by Felipe738743872** [kivy/buildozer#1190]
### Versions

* Python: 3.6.9
* OS: VM 0.7 Xubuntu
* Buildozer: 1.2.0

### Description

Hello, the audio works but the video not working :(

### buildozer.spec
Command:
```sh
buildozer android logcat | grep python
```

main.py:
```
from kivy.app import App
from kivy.uix.videoplayer import VideoPlayer


class APPPP(App):
    def build(self):
        video = VideoPlayer(source='song.mp4')
        return video


if __name__ == '__main__':
    APPPP().run()
```

Spec file:
```
[app]
title = My Application
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,mp4
version = 0.1
requirements = python3, kivy, ffpyplayer, ffpyplayer_codecs, openssl
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.arch = armeabi-v7a
p4a.branch = master
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0
[buildozer]
log_level = 2
warn_on_root = 1
```

### Logs

```
07-13 20:01:31.697  3041  3075 I python  : Android kivy bootstrap done. __name__ is __main__
07-13 20:01:31.697  3041  3075 I python  : AND: Ran string
07-13 20:01:31.697  3041  3075 I python  : Run user program, change dir and execute entrypoint
07-13 20:01:31.782  3041  3075 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.myapp/files/app/.kivy/logs/kivy_20-07-13_2.txt
07-13 20:01:31.782  3041  3075 I python  : [INFO   ] [Kivy        ] v1.11.1
07-13 20:01:31.782  3041  3075 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
07-13 20:01:31.783  3041  3075 I python  : [INFO   ] [Python      ] v3.8.1 (default, Jul 13 2020, 23:52:45) 
07-13 20:01:31.783  3041  3075 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
07-13 20:01:31.783  3041  3075 I python  : [INFO   ] [Python      ] Interpreter at ""
07-13 20:01:32.478  3041  3075 I python  : [INFO   ] [Factory     ] 184 symbols loaded
07-13 20:01:32.723  3041  3075 I python  : [INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.2.0.dev0
07-13 20:01:32.723  3041  3075 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_ffpyplayer, img_gif (img_pil ignored)
07-13 20:01:32.749  3041  3075 I python  : [INFO   ] [Text        ] Provider: sdl2
07-13 20:01:32.762  3041  3075 I python  : [INFO   ] [VideoFFPy   ] Using ffpyplayer 4.2.0.dev0
07-13 20:01:32.762  3041  3075 I python  : [INFO   ] [Video       ] Provider: ffpyplayer(['video_ffmpeg'] ignored)
07-13 20:01:32.784  3041  3075 I python  : [INFO   ] [Window      ] Provider: sdl2
07-13 20:01:32.804  3041  3075 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
07-13 20:01:32.805  3041  3075 I python  : [INFO   ] [GL          ] Backend used <sdl2>
07-13 20:01:32.805  3041  3075 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@331.0 (GIT@26c925f, Ia74c9b5270) (Date:10/10/18)'>
07-13 20:01:32.805  3041  3075 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
07-13 20:01:32.805  3041  3075 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 540'>
07-13 20:01:32.806  3041  3075 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
07-13 20:01:32.806  3041  3075 I python  : [INFO   ] [GL          ] Texture max size <16384>
07-13 20:01:32.806  3041  3075 I python  : [INFO   ] [GL          ] Texture max units <16>
07-13 20:01:32.823  3041  3075 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
07-13 20:01:32.824  3041  3075 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
07-13 20:01:32.913  3041  3075 I python  : [WARNING] [Base        ] Unknown <android> provider
07-13 20:01:32.914  3041  3075 I python  : [INFO   ] [Base        ] Start application main loop
07-13 20:01:32.915  3041  3075 I python  : [ERROR  ] [Image       ] Error loading texture song.mp4
07-13 20:01:32.918  3041  3075 I python  : [INFO   ] [GL          ] NPOT texture support is available
07-13 20:01:32.920  3041  3075 I python  : [WARNING] Deprecated property "<BooleanProperty name=play>" of object "<kivy.uix.video.Video object at 0xd00122c8>" was accessed, it will be removed in a future version
07-13 20:01:34.975  3041  3075 I python  : [WARNING] [Image       ] Unable to load image </data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/data/images/image-loading.gif>
07-13 20:01:34.976  3041  3075 I python  : [ERROR  ] [Image       ] Error loading texture data/images/image-loading.gif
07-13 20:01:35.016  3041  3084 I python  :  Exception in thread Next frame:
07-13 20:01:35.016  3041  3084 I python  :  Traceback (most recent call last):
07-13 20:01:35.016  3041  3084 I python  :    File "/home/kivy/Desktop/APP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/threading.py", line 932, in _bootstrap_inner
07-13 20:01:35.016  3041  3084 I python  :    File "/home/kivy/Desktop/APP/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/jnius/__init__.py", line 84, in jnius_thread_hook
07-13 20:01:35.017  3041  3084 I python  :    File "/home/kivy/Desktop/APP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/threading.py", line 870, in run
07-13 20:01:35.017  3041  3084 I python  :    File "/home/kivy/Desktop/APP/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/video/video_ffpyplayer.py", line 240, in _next_frame_run
07-13 20:01:35.017  3041  3084 I python  :  AttributeError: module 'time' has no attribute 'clock'
07-13 20:01:35.030  3041  3114 I python  : [WARNING] [ffpyplayer  ] [swscaler @ 0xcc410000] No accelerated colorspace conversion found from yuv420p to rgba.
```

**Comment by HenriVDD** [comment]
Hello,

I have the exact same issue, the sound works fine but not the video

Versions

    Python: 3.6.9
    OS: Windows and VM Ubuntu18.04 
    Buildozer: 1.2.0

With pretty much the same buildozer.spec

That error sounds weird to me as the "AttributeError: module 'time' has no attribute 'clock'" looks like python3.8 error because time.clock is deprecated in python3.8. But I use python 3.6.9

Does someone as an idea on how to solve this ? Thanks

**Comment by matham** [comment]
You have to use kivy master, where this is fixed.

**Comment by HenriVDD** [comment]
Thank you @matham for your reply, but even with the master version of buildozer I still have the same error. 

python  : Traceback (most recent call last):
python  :   File "/home/masterni/videoapp/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/threading.py",line 932, in _bootstrap_inner
python  :   File "/home/masterni/videoapp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myvideoapp/jnius/__init__.py",line 84, in jnius_thread_hook
python  :   File"/home/masterni/videoapp/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/threading.py",line 870, in run
python  :   File"/home/masterni/videoapp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myvideoapp/kivy/core/video/video_ffpyplayer.py",line 240, in _next_frame_run
python  : AttributeError: module 'time' has no attribute 'clock'
python  : [WARNING] [ffpyplayer  ] [swscaler @ 0xc403b000] No acceleratedcolorspace conversion found from yuv420p to rgba.

I imagine that buildozer somehow doesn't use by default kivy master. Is there any way to specify which version of kivy using to package an apk with buildozer? Thanks in advance.

**Comment by HenriVDD** [comment]
Thanks a lot @matham, now it works if I specify kivy==master in the requirements of the buidlozer.spec
