### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED only on Android

### ISSUE THREAD

**Issue by Arelfox** [kivy/buildozer#1502]
### Versions

* Python: 3
* OS: Android
* Buildozer: 1.4.0 (?)

### Description

When loading an AsyncImage, it shows "...[SLL: CERTIFICATE_VERIFY_FAILED]..." on logcat and doesn't load the image in the app. This doesn't happen on my computer. There was another issue posted, but their solution did not work for me.

### buildozer.spec
Command:
buildozer android run
```

Spec file:
```
can't copy to computer, has certifi in permissions though
```

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/kivy/pull/7994 on `kivy/kivy` ( You can easily target the `kivy` `master` version by using `kivy==master` in your `buildozer.spec` file)

**Comment by magowiz** [comment]
I still have this issue using kivy master:
02-11 14:41:35.334 2656 3297 I python : [INFO ] [Video ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
02-11 14:41:36.569 2656 3297 I python : [INFO ] [GL ] NPOT texture support is available
02-11 14:41:38.133 2656 3297 I python : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

changed kivy==2.1.0 to kivy==master in buildozer.spec, deleted the whole build directory for buildozer and rebuilt the package

the library has issue fetching data is meteostat which relies on pandas for this, I will show you here relevant versions for packages:
using last version of buildozer: 1.5.0

from buildozer.spec requirements:
kivy==master, meteostat, pandas, certifi, python3

p4a.fork kivy and p4a.branch develop

Please tell me if this is another issue or if I need to upgrade some package or if it is better to open another bug report.
