### ISSUE TITLE
keka failed to download (OS X El Capitan)

### ISSUE THREAD

**Issue by TimSC** [kivy/buildozer#427]
I'm a relative beginner in osx... I'm using El Capitan.

	# check if Kivy.app exists in local dir
	# Downloading kivy...
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
		                             Dload  Upload   Total   Spent    Left  Speed
	100   178  100   178    0     0    580      0 --:--:-- --:--:-- --:--:--   581
	100   162  100   162    0     0    149      0  0:00:01  0:00:01 --:--:--   250
	curl: no URL specified!
	curl: try 'curl --help' or 'curl --manual' for more information
	Traceback (most recent call last):
	  File "/usr/local/bin/buildozer", line 9, in <module>
		load_entry_point('buildozer==0.33dev', 'console_scripts', 'buildozer')()
	  File "/Library/Python/2.7/site-packages/buildozer/scripts/client.py", line 13, in main
		Buildozer().run_command(sys.argv[1:])
	  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 1028, in run_command
		self.target.run_commands(args)
	  File "/Library/Python/2.7/site-packages/buildozer/targets/osx.py", line 234, in run_commands
		func(args)
	  File "/Library/Python/2.7/site-packages/buildozer/targets/osx.py", line 247, in cmd_debug
		self.buildozer.prepare_for_build()
	  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 171, in prepare_for_build
		self.target.check_requirements()
	  File "/Library/Python/2.7/site-packages/buildozer/targets/osx.py", line 101, in check_requirements
		self.ensure_kivyapp()
	  File "/Library/Python/2.7/site-packages/buildozer/targets/osx.py", line 89, in ensure_kivyapp
		self.download_kivy(kivy_app_dir)
	  File "/Library/Python/2.7/site-packages/buildozer/targets/osx.py", line 65, in download_kivy
		cwd=cwd)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
		raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command '('curl', '-o', 'http://www.kekaosx.com/release/Keka-1.0.4-intel.dmg')' returned non-zero exit status 2
	Tims-MacBook-Pro:explore-game Tim$ 

I noticed http://www.kekaosx.com/release/Keka-1.0.4-intel.dmg no longer exists.

I tried: brew install Caskroom/cask/keka

Now it fails with:

	# Downloading kivy...
	
	7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
	p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,2 CPUs x64)
	Modified by aONe for Keka
	
	Scanning the drive for archives:
	1 file, 162 bytes (1 KiB)
	
	Extracting archive: Kivy2.7z
	ERROR: Kivy2.7z
	Kivy2.7z
	Open ERROR: Can not open the file as [7z] archive

I notice the download_kivy function refers to a url starting with http://kivy.org/downloads/tests/ which no longer exists.

It is also weird that it is trying to install kivy when I think it is already available on my system.

**Comment by jbillhei** [comment]
I had the same issue. I manually installed Keka from the dmg instead of using homebrew.  (it's still available on the website, just not at the link buildozer expects).

By manually downloading https://kivy.org/downloads/1.9.1/Kivy-1.9.1-osx-python2.7z and renaming it to Kivy2.7z, you can get past this step.  It wants to put the file in the .buildozer/osx/platform/kivy-sdk-packager-master/osx directory.

buildozer will then break again on some missing deps.  Make sure you pip install docopt and pip install sh.  You might have some other missing deps as well, so check for that first if you get an error.

I got it to start building at this stage.  Then it fails again, after getting tantalizingly close to producing a .dmg file: AttributeError: 'Buildozer' object has no attribute 'builddir'

Up to this point, I was using the current release.  Switching to the master branch fixes that problem.

Also don't forget your app entry point must be main.py.

At this point, I've got a running app on OS X, yay!

I hope that helps!

**Comment by TinBane** [comment]
I get the same issue:
`(cellscanner) ABIS:inCellScanning adrian$ buildozer osx debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for osx
# Check if kivy-sdk-packager exists
# kivy-sdk-packager found at /Users/adrian/python/inCellScanning/.buildozer/osx/platform
# check if Kivy.app exists in local dir
# Downloading kivy...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    346      0 --:--:-- --:--:-- --:--:--   346
100   162  100   162    0     0    105      0  0:00:01  0:00:01 --:--:--   650

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
1 file, 162 bytes (1 KiB)

Extracting archive: Kivy2.7z
ERROR: Kivy2.7z
Kivy2.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Is not archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
Traceback (most recent call last):
  File "/Users/adrian/Envs/cellscanner/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/__init__.py", line 1026, in run_command
    self.target.run_commands(args)
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/targets/osx.py", line 234, in run_commands
    func(args)
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/targets/osx.py", line 247, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/__init__.py", line 172, in prepare_for_build
    self.target.check_requirements()
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/targets/osx.py", line 101, in check_requirements
    self.ensure_kivyapp()
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/targets/osx.py", line 89, in ensure_kivyapp
    self.download_kivy(kivy_app_dir)
  File "/Users/adrian/Envs/cellscanner/lib/python2.7/site-packages/buildozer/targets/osx.py", line 75, in download_kivy
    'x', '{}.7z'.format(kivy)), cwd=cwd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('Keka.app/Contents/Resources/keka7z', 'x', 'Kivy2.7z')' returned non-zero exit status 2`

Then I follow up with 
`cat .//.buildozer/osx/platform/kivy-sdk-packager-master/osx/Kivy2.7z
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
`

So, it looks like the download for kivy2.7z is failing. It's not catching the 404 code, so it's saving the contents of the error as a .7z and trying to open it. I'm going to work around it the same way as the above, but I suggest changing the code so it errors correctly on a 404, and fixing the link.

**Comment by mattbryson** [comment]
Any progress on this? I'm having the same issues....

**Comment by oukiar** [comment]
me too :s

**Comment by KeyWeeUsr** [comment]
Dunno how this works on Mac, but with wget/curl we could fetch just the `http://www.kekaosx.com/release/` URL because it returns the actual release. Or fetch the latest one from [GitHub](https://github.com/aonez/Keka/releases/) as those links are more stable than website links (imo).

**Comment by tito** [comment]
@oukiar @mattbryson please try buildozer/master to see if it's ok :)

**Comment by tito** [comment]
Reopen if it not the case

**Comment by oukiar** [comment]
Hi @tito , I try again with buildozer/master and still the same error, for some reason "https://github.com/aonez/Keka/releases/download/v1.0.8/Keka-1.0.8.dmg" fails to download, I try with 

check_call(
                    ('curl', '-O', 'http://www.kekaosx.com/release/Keka-1.0.8.dmg')

and works ok, the DMG is generated.

Now I start to have the problem that in osx do not install the requirements, for now netifaces, but it seems that only generates the .dmg when the requirement is only kivy (sqlite3 does not seem to work either)

**Comment by tito** [comment]
@oukiar i fixed the link with the one you provided

**Comment by mattbryson** [comment]
thanks @tito  I tried again, it still appears to download Kivy when it is already on the system, but it is now installing kivy ok.  However, it then fails with....

```

# Extracting and installing Kivy...
# Install platform
# Check application requirements
# Check garden requirements
# Compile platform
# Build the application #1
# Package the application
# Building package
# Create myapp.app
Traceback (most recent call last):
  File "package_app.py", line 45, in <module>
    from docopt import docopt
ImportError: No module named docopt
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/buildozer/__init__.py", line 1020, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/osx.py", line 237, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/osx.py", line 253, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/site-packages/buildozer/__init__.py", line 211, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/osx.py", line 158, in build_package
    check_output(cmd, cwd=cwd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['python', 'package_app.py', '/Users/Matt/env/pong/.buildozer/osx/app', '--appname=myapp', '--bundlename=My Application', '--bundleid=org.test', '--bundleversion=0.1', '--displayname=My Application']' returned non-zero exit status 1
```

**Comment by oukiar** [comment]
install the missing module with

pip install docopt

**Comment by mattbryson** [comment]
That fixes that step, and then it errors again with....

```
NameError: global name 'sh' is not defined
```

```
Traceback (most recent call last):
  File "package_app.py", line 234, in <module>
    main(arguments)
  File "package_app.py", line 217, in main
    bootstrap(source_app, appname, confirm)
  File "package_app.py", line 79, in bootstrap
    sh.cp('-a', source_app, appname)
NameError: global name 'sh' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/buildozer/__init__.py", line 1020, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/osx.py", line 237, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/osx.py", line 253, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/site-packages/buildozer/__init__.py", line 211, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/osx.py", line 158, in build_package
    check_output(cmd, cwd=cwd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['python', 'package_app.py', '/Users/Matt/env/pong/.buildozer/osx/app', '--appname=myapp', '--bundlename=My Application', '--bundleid=org.test', '--bundleversion=0.1', '--displayname=My Application']' returned non-zero exit status 1
```

**Comment by oukiar** [comment]
I also had those problems, install this:

pip install colorama appdirs sh jinja2

**Comment by mattbryson** [comment]
ha!  its working now - can these dependencies not be installed as part of `buildozer`?

**Comment by mattbryson** [comment]
well, it builds a .dmg, but then the resulting app just boots and shuts down again.

I was expecting the packager to build an app that runs my app?  

It appears to just stick my app into the kivy.app....

**Comment by oukiar** [comment]
yes, im too trying with it, for now this helloworld build and works installed from the dmg
https://github.com/oukiar/hello

You can check the kivy logs for more detail about the problem running your new packed app
