### ISSUE TITLE
The "android" command is deprecated

### ISSUE THREAD

**Issue by mimi89999** [kivy/buildozer#519]
When building a Buildozer app with the latest SDK, I get:
```
# Android SDK found at /home/michel/android-sdk
# Android NDK found at /home/michel/android-sdk/ndk-bundle
# Run '/home/michel/android-sdk/tools/android list sdk -u -e'
# Cwd /home/michel/.buildozer/android/platform
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Timed out waiting for input.
To suppress this prompt, run with --use-sdk-wrapper or set USE_SDK_WRAPPER.
# Command failed: /home/michel/android-sdk/tools/android list sdk -u -e
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

Buildozer should use sdkmanager commands now.

**Comment by misl6** [comment]
For a quickly workaround just go back to "SDK Tools, Revision 25.3.0"

**Comment by mimi89999** [comment]
This won't help since I am building on F-Droid...

**Comment by lzps** [comment]
```bash
cd ./.buildozer/android/platform/python-for-android-master/
git pull origin master

export USE_SDK_WRAPPER=True
```

**Comment by inclement** [comment]
This should be fixed for sdl2 by https://github.com/kivy/python-for-android/pull/1071 , but it needs testing.

**Comment by comodoro** [comment]
I updated to current repository version:

`pip install git+https://github.com/kivy/buildozer.git`

and have version `buildozer==0.34.dev0`

but still encountered the prompt

**Comment by inclement** [comment]
@comodoro You might need to clean any exsisting downloaded SDK.

**Comment by comodoro** [comment]
Confirmed, I was using my existing up-to-date SDK (which does not work anyway), but deleting ~/.buildozer has helped (with this particular prompt)

**Comment by Ryan-ED** [comment]
Is downgrading still the only option to fix this issue?

**Comment by inclement** [comment]
Closed by #806
