### ISSUE TITLE
buildozer fails at installing platfrom

### ISSUE THREAD

**Issue by JonasEc** [kivy/buildozer#726]
### Versions

* Python: 2.7
* OS: Linux Ubuntu 18.04
* Kivy: 1.9.1
* Cython: 0.29

### Description

Running "buildozer android debug deploy run" errors out immediately at 
```
# Install platform
# Run 'git clone -b stable --single-branch https://github.com/kivy/python-for-android.git python-for-android-new-toolchain'
# Cwd [my buildozer folder]
Cloning into 'python-for-android-new-toolchain'...
# Run 'pip install -q --user '
# Cwd None
ERROR: You must give at least one requirement to install (see "pip help install")
# Command failed: pip install -q --user 
```

**Comment by AndreMiras** [comment]
Fixed in https://github.com/kivy/buildozer/pull/724

**Comment by JonasEc** [comment]
I used the git zip install from the #724 answer but the exact same error persists.

**Comment by AndreMiras** [comment]
That's unexpected. It solves it for me :thinking: 
```
pip install --user --upgrade https://github.com/kivy/buildozer/archive/618faa076d81fbdc11a4284c1d7690045422b5f9.zip
```

**Comment by OptimusGREEN** [comment]
i did a bulldozer android update straight after the zip install and all is well.

**Comment by JonasEc** [comment]
Hm, it seems the issue is that the above installs to /root/.local/bin/ rather than the "normal" python space, meaning that it isn't on path and hence I was still calling the previous version. How do I change it to install to default user directory for python?

**Comment by OptimusGREEN** [comment]
I half lied earlier. Worked on my MacBook but not my iMac. Weird.

**Comment by JonasEc** [comment]
I installed in the correct folder and purged all traces of previous buildozer builds and the same thing is happening.

**Comment by Huyston** [comment]
If you do 
`buildozer android debug deploy run`
Then you can't accept the question that buildozer asks. For that you should run
`buildozer -v android debug deploy run`
With the verbose tag. I think this shouldn't be the case. Because the origin of the error is obscured from the user.
